"""add webhook_sent_at

Revision ID: b0e545c785a1
Revises: 0001
Create Date: 2026-10-08 12:51:24.242116
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0e545c785a1'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('webhook_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'webhook_sent_at')
    # ### end Alembic commands ###
